include:
  # Cornix 左手（単体運用）
  - board: cornix_left
    # shield: cornix_indicator
    artifact-name: cornix_left

  # Cornix 右手
  - board: cornix_right
    # shield: cornix_indicator
    artifact-name: cornix_right

  # 設定リセット用ファーム
  - board: cornix_right
    shield: settings_reset
    artifact-name: reset
